//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class helloworlds
    {
        public int ID { get; set; }
        public string man { get; set; }
        public Nullable<int> age { get; set; }
        public string introduce { get; set; }
        public string skill { get; set; }
        public string href { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
